API JSON support
hestiacp/hestiacp pull request #1465
Opened 2020-12-13 22:28 UTC by danielalexis

This enables native support for JSON (with backwards compatibility)
Heres an example using NodeJS (tested)
```js
//NodeJS Script
//You must have the axios module installed
const axios = require('axios')

//Admin Credentials
const hst_hostname = 'server.hestiacp.com'
const hst_port = 8083
const hst_username = 'admin'
const hst_password = 'p4ssw0rd'
const hst_returncode = 'yes'
const hst_command = 'v-add-user'

//New account details
const username = 'demo';
const password = 'd3m0p4ssw0rd';
const email = 'demo@gmail.com';
const package = 'default';
const first_name = 'Rust';
const last_name = 'Cohle';

const data_json = {
'user': hst_username,
'password': hst_password,
'returncode': hst_returncode,
'cmd': hst_command,
'arg1': username,
'arg2': password,
'arg3': email,
'arg4': package,
'arg5': first_name,
'arg6': last_name
}

const data = JSON.stringify(data_json)

axios.post('https://'+hst_hostname+':'+hst_port+'/api/', data)
.then(function (response) {
    console.log(response.data);
    console.log("0 means successful")
})
.catch(function (error) {
    console.log(error);
});
```

2020-12-20 22:55 UTC, jaapmarcus requested changes

2020-12-20 22:55 UTC, jaapmarcus commented on web/api/index.php
> +    api($_POST['hash'], $_POST['user'], $_POST['password'], $_POST['returncode'], $_post['cmd'], $_POST['arg1'], $_POST['arg2'], $_POST['arg3'], $_POST['arg4'], $_POST['arg5'], $_POST['arg6'], $_POST
$_post['cmd'] should be $_POST['cmd'];

2020-12-20 22:55 UTC, jaapmarcus commented on web/api/index.php
> +        $fp = fopen($_hst_arg2, 'w');
$_hst_arg2 / $_hst_arg1 is never created 

It should be $hst_arg instead

2020-12-20 23:04 UTC, danielalexis commented
Fixed both

2020-12-21 09:02 UTC, jaapmarcus approved these changes

2020-12-21 09:04 UTC, merged