Initial Smarthost Commit
hestiacp/hestiacp pull request #1591
Opened 2021-01-26 05:42 UTC by cmstew

Adds smarthost capabilities to Hestia.
- You may optionally set a global smarthost
- You may also optionally set a different smarthost per domain.

2021-01-26 12:59 UTC, jaapmarcus requested changes

2021-01-26 12:59 UTC, jaapmarcus commented on install/upgrade/versions/1.3.3.sh
> +    fi
Whole script didn't get called during the upgrade we should rename everything to 1.4.0.sh

2021-01-26 13:00 UTC, jaapmarcus commented
For install/upgrade/versions/1.3.3.sh

This has been discussed in Discord we should  rename it to 1.4.0.sh but the upgrade script didn't call.

2021-01-30 08:17 UTC, jaapmarcus commented
Entering the password is still required when updating webmail system / dkim / ssl
<img width="340" alt="Screenshot 2021-01-30 at 09 16 28" src="https://user-images.githubusercontent.com/9754650/106351332-ef795c00-62db-11eb-8a7a-17e5392209ee.png">

2021-01-30 08:19 UTC, jaapmarcus commented
I haven't checked the code yet:

<img width="714" alt="Screenshot 2021-01-30 at 09 18 37" src="https://user-images.githubusercontent.com/9754650/106351394-41ba7d00-62dc-11eb-9120-173b165b48b2.png">

This is made before saving

2021-01-30 08:52 UTC, jaapmarcus commented
https://github.com/cmstew/hestiacp/blob/d30ed2c4b7e16f22178e69e99a661957850fc687/bin/v-add-mail-domain-smtp-relay#L56-L65

Add check if vars all ready exist currently they are added multiple times

2021-01-30 15:46 UTC, cmstew commented
> Entering the password is still required when updating webmail system / dkim / ssl
> <img alt="Screenshot 2021-01-30 at 09 16 28" width="340" src="https://user-images.githubusercontent.com/9754650/106351332-ef795c00-62db-11eb-8a7a-17e5392209ee.png">

This is actually resolved now.

2021-01-30 17:07 UTC, cmstew commented
> https://github.com/cmstew/hestiacp/blob/d30ed2c4b7e16f22178e69e99a661957850fc687/bin/v-add-mail-domain-smtp-relay#L56-L65
> 
> Add check if vars all ready exist currently they are added multiple times
> 
> ```
>  U_SMARTHOST='yes' U_SMARTHOST_HOST='mail.smtp2go.com' U_SMARTHOST_PORT='587' U_SMARTHOST_USERNAME='xxx' U_SMTP_RELAY='true' U_SMTP_RELAY_HOST='mail.smtp2go.com' U_SMTP_RELAY_PORT='2525' U_SMTP_RELAY_USERNAME='xxx'
> ```
> 
> We should also save the password incase of a restore....

- Added checks for vars
- Added saving password
- Added restore capability

2021-02-02 13:23 UTC, jaapmarcus approved these changes

2021-02-02 13:25 UTC, jaapmarcus commented
Changes are working fine.

Pushed 2 small changes when password of smtp relay was changed it didn't update propperly

2021-02-02 13:48 UTC, merged