Fix for one cause of Letsencrypt 400 Authorization Pending Error
hestiacp/hestiacp pull request #2066
Opened 2021-08-17 16:48 UTC by Anubioz

Forces nginx to serve .well-known when obtaining LE certificates even when .htaccess urlrewrite is used to rewrite .well-known somewhere it shouldn't be, like:
RewriteRule ^(.*)$ /index.php [L]
which would otherwise result in fail

2021-08-18 13:27 UTC, jaapmarcus commented
Even with the old "templates"

```
RewriteEngine On
RewriteRule ^(.*) index.php [L,QSA]  
```

Will still work fine if I go: https://domain.com/.well-known/acme-challenge/awefawefawe 

I will see:

`awefawefawe.q7cTXUlY6G2YNsfw4P-x0d0k0RxRCW9fFGRQBk04bLc` as output instead 

If you type in: 

https://domain.com/.well-known/ 
I get 
`string(13) "/.well-known/"`

Or any https://domain.com/hestiacp

 `string(9) "/hestiacp"`

It should probably not hurt it. So it should be fine...

2021-08-18 14:50 UTC, Anubioz commented
adding:
ErrorDocument 404 /index.php

should break it for sure )

2021-08-18 19:40 UTC, jaapmarcus commented
> adding:
> ErrorDocument 404 /index.php
> 
> should break it for sure )

Haven't been able to recreate your issue on my test server with different .htaccess files. Could you please send us the following info:

1. Template used
2. htaccess used 
3. Domain name 
4. Log file located in /var/log/hestia/LE-user-domain.log with the domain. 

If you don't want to share the email in public please send a email to info@hestiacp.com  so we can have a look at it. 

Our experience most issues happens when:
1. Cloudflare  is used with proxy enabled  and before ssl has been enabled / issues
2. Forcing SSL while generate new certificate
3. Issues with DNS and ipv6 enabled 
4. Issues with Nginx not reloading due to error in templates  / settings

2021-08-25 07:05 UTC, jaapmarcus requested changes
Please provide us with the request questions so far this change should not affect any thing.

2021-09-09 17:00 UTC, ScIT-Raphael commented
Due to missing informations, I'll close this PR. If possible, please answer @jaapmarcus's request so we can proceed.

2021-09-09 17:00 UTC, closed without merging