Change how apt keys are downloaded
hestiacp/hestiacp pull request #2299
Opened 2021-12-17 14:53 UTC by jaapmarcus

2021-12-18 08:24 UTC, ScIT-Raphael requested changes
Shouldnt we also include the changes in existing hestia versions over the upgrade script?

2021-12-22 03:45 UTC, kpapad904 commented on install/upgrade/versions/1.5.3.sh
> +        curl -s https://mariadb.org/mariadb_release_signing_key.asc | gpg --dearmor | tee /usr/share/keyrings/mariadb-keyring.gpg >/dev/null 2>&1
line 71 should be:

https ://mirror.mva-n.net/mariadb//repo/$mariadb_v/$VERSION $codename main

2021-12-22 06:22 UTC, jaapmarcus commented
Changed it

2021-12-22 20:47 UTC, kpapad904 commented
Actually it seems that the correct syntax for install/upgrade/versions/1.5.3.sh should be:

`https ://mirror.mva-n.net/mariadb//repo/$mariadb_v/$os $codename main
`

Note: Currently there is an inconsistency between the install and upgrade scripts in how they derive the variables $VERSION and $os …
```
VERSION="$(lsb_release -s -r)"
VERSION=‘debian’
```

For consistency reasons $VERSION should be the same in all 3 scripts (install/hst-install-debian.sh install/hst-install-ubuntu.sh and install/upgrade/versions/1.5.3.sh)

2021-12-22 21:49 UTC, jaapmarcus commented
Don't know why both VERSION and OS are hardcoded... 

Made some minor changes

2022-01-16 14:38 UTC, ScIT-Raphael approved these changes

2022-01-16 14:38 UTC, merged