Unset domain_redirect to prevent false redirects on LE Update
hestiacp/hestiacp pull request #2410
Opened 2022-02-08 11:02 UTC by ScIT-Raphael

According to https://forum.hestiacp.com/t/redirect-301-nightmare/5536, thanks for reporting!

2022-02-08 11:28 UTC, jaapmarcus requested changes

2022-02-08 11:28 UTC, jaapmarcus commented on func/syshealth.sh
> +    unset domain_redirect
Is not needed here. We should add Redirect + Redirect in here to add it if it doesn't exists

2022-02-08 12:11 UTC, jaapmarcus commented
It is:

https://github.com/hestiacp/hestiacp/blob/0b70d08f409efa07070876f7547577a1cfd94f30/bin/v-update-letsencrypt-ssl#L93

That cause the issue.

parse_object_kv_list_non_eval  doesn't update non existing keys

2022-02-09 19:00 UTC, ScIT-Raphael commented
Fixed by #2411

2022-02-09 19:00 UTC, closed without merging