Adds the ability to use the web api with non-admin users
hestiacp/hestiacp pull request #2474
Opened 2022-03-11 13:04 UTC by jhmaverick

* Adds option to define a user for the key and the scripts that can be used;
* List of scripts that can be used by non-admin users with "user" argument position for validation;
* Keys generated for admin can still have access to all scripts but it is possible to limit which ones can be used;
* Keys in the old format will run as admin and have access to all scripts.

2022-03-11 17:37 UTC, jlguerrerosanz commented
Great addition. Thank you!

2022-03-11 19:57 UTC, jlguerrerosanz commented
I would love to know how to properly use this new feature with the dns-cluster user.

Maybe an example in the script docs.

2022-03-12 08:04 UTC, jaapmarcus requested changes
It looks fine it would be nice to allow the use of presets:

For example when using DNS cluster set preset "as"  dns-cluster and you don't have to list the fulll list you need.

Other examples:
phpmyadmin-sso
purge-nginx-cache


whmcs / billing sytem.. And so on

2022-03-12 08:04 UTC, jaapmarcus commented on bin/v-generate-api-key
> +echo "USER:    $user"
We should add an option to supply an argument that allows output as json for Web UI

2022-03-12 08:04 UTC, jaapmarcus commented on bin/v-list-api-key
> +is_format_valid 'key'
.. will also be considered a valid key with is_format_valid 'key'

Validate with v-check-api-key to make sure it it valid 

 is_format_valid 'key' is used to valid config keys in user.conf for example...

2022-03-12 08:05 UTC, jaapmarcus commented
> I would love to know how to properly use this new feature with the dns-cluster user.
> 
> Maybe an example in the script docs.

At some point we need to update the docs anyway

2022-03-23 15:41 UTC, jhmaverick commented on bin/v-generate-api-key
> +echo "USER:    $user"
I added a third argument in the script to make it possible to change the output

2022-03-23 15:41 UTC, jhmaverick commented on bin/v-list-api-key
> +is_format_valid 'key'
As this script and the "v-check-api-key" serve similar purposes, I removed the "v-list-api-key" and added the return for the v-check-api-key"

2022-03-23 15:46 UTC, jhmaverick commented
I made some changes to simplify using the functionality and added the option for script groups in the API. The way the script obtains the position of the "USER" parameter in scripts has also been changed.

Initially I just added 2 groups "mail-accounts" and "purge-nginx-cache". I didn't add a group for "dns-cluster" because I don't know exactly which scripts are ideal for this functionality and I also noticed that some of his scripts don't have the "USER" argument to limit actions only to the defined user.

2022-03-25 13:45 UTC, jaapmarcus commented on bin/v-list-api-key
> +is_format_valid 'key'
👍🏼

2022-03-29 12:20 UTC, jaapmarcus commented
Merged this PR in a different branch + Some other changes Quick installers 

#2503

2022-03-29 12:20 UTC, jaapmarcus commented
Sorry the wrong one :)

2022-04-01 10:03 UTC, jaapmarcus commented
Did. some testing and it works fine:

Some small remarks:
Because we overwrite main.sh each update users can't update the "group" list
Some "keys" benefit even from restricting for the admin user:

https://github.com/jaapmarcus/hestiacp/tree/feature/nonadminapi-changes

Should solve this issue.

- Only thing "left" is log any kind of "faulty" usage as they are currently only "returned" with an exit code but not logged on the server side
- Make v-list-api-keys with a list of the current active "keys" 
- UI to view it in admin panel and allow admin create the keys...
-

2022-04-01 18:16 UTC, jhmaverick commented
I liked the folder for groups, it really got better.

I think the first 2 items will be simple to do. Maybe the interface part takes more time. But I'll see what I can do.

2022-04-01 18:47 UTC, jaapmarcus commented
Fist two items should no issues... And relative easy...

"My" changes haven't been merged into this branch feel free to do so...

2022-04-16 14:49 UTC, jhmaverick commented
I found some problems when listing the keys, as they were composed of just one hash, the key would need to be exposed on the panel to display or even to control the delete and display events... So I thought it best to create one new system and leave the old one as a legacy.

#2535 Here is the version with the new commands and management interface

2022-04-16 14:59 UTC, jaapmarcus commented
https://github.com/hestiacp/hestiacp/pull/2535 

Will close this one

2022-04-16 14:59 UTC, closed without merging