Set FORWARD chain default policy to DROP
hestiacp/hestiacp pull request #2528
Opened 2022-04-12 19:59 UTC by jaydio

In iptables, the FORWARD chain is used for packets passing THROUGH it, meaning,  packets not addressed to or originating from the local machine. With the FORWARD default policy set to ACCEPT, all traffic between networks that are connected to the local machine is allowed, essentially turning it into a router.

If the machine only has one interface, this won't be much of a problem. However, say you hooked it up to a VPN for remote management access. This could allow a host that's located on the VPN side to use the local machine as a gateway to access networks that the local machine is connected to. For this to work the local machine would have to have IP forwarding enabled (sysctl → net.ipv4.ip_forward = 1) which on most platforms isn't the case by default. Even though, it's a sensible thing to set the default policy of the FORWARD chain to DROP.

2022-04-12 20:44 UTC, ioannidesalex commented
Since we are discussing default settings, personally I am not in favour with switching FORWARD policy to DROP.

As you said it's a sensible change that might break a lot of current setups. There is no one-size-fits-all for things like that, but I believe that if a system admin knows how to add multiple interfaces, hook the server to a VPN etc, he/she would definitely know how to amend the FORWARD policy :)

2022-04-12 21:28 UTC, jaapmarcus commented
You can't drop by default as it would break systems. As it becomes a default setting it is also not "changeable" by the user.  Unless we add an option to disable / Enable it via  the settings

2022-04-12 21:39 UTC, ioannidesalex commented
I guess proposed PR (v-update-firewall) will impact current production servers as well.

Having it as an option in settings is a good idea. But In my opinion FORWARD default value should stat as is.

2022-04-12 21:42 UTC, jaapmarcus commented
> I guess proposed PR (v-update-firewall) will impact current production servers as well.
> 
> Having it as an option in settings is a good idea. But In my opinion FORWARD default value should stat as is.

Yes as you run v-update-firewall it will "update" the new rules

2022-04-14 05:38 UTC, jaapmarcus requested changes
See comments as this will most likely current setups if used for VPN...

2022-04-14 14:03 UTC, jaydio commented
Fair comments, considering that most users will probably have auto-updates enabled (we don't). Otherwise, making "breaking changes" should be fine as long as they're sensible and users are informed in the release notes.

When it comes to specifying defaults, best practice suggests being as conservative/restrictive as possible. So I'd expect any type of custom scenario, such as routed access via VPN, to be manually configured by the user. For this purpose, `$HESTIA/data/firewall/custom.sh` exists - see https://forum.hestiacp.com/t/how-to-add-iptables-rules-to-server-with-hestia/4596/12 as well.

I know there is more important stuff to deal with. Will just close this PR for now.

2022-04-14 14:03 UTC, closed without merging