Feature/newapisystem
hestiacp/hestiacp pull request #2535
Opened 2022-04-16 14:46 UTC by jhmaverick

New API system with permission control and use with non-admin users.

Differences in handling keys:

* Each key is composed of an identification hash and a secret hash;
* Keys are linked with APIs and each API defines the scripts that can be used by it;
* To avoid conflicts with the keys of the old version, the new version is saved in "data/access-keys" and they have different management commands.
* API options are under "data/api".
* Non-admin users can use the APIs with limitations:
    * Scripts that have the "user" argument can only be used with the key's user;
    * Only APIs with ROLE "user" can be selected when creating a key;
    * Suspended users cannot consume from the API;
    * Key usage logs are also saved for the user;
    * The use of APIs by users can be disabled in the settings.
* Management of keys through the Web interface;
* Separate options to enable API versions in settings (It is possible to enable only for admin or for all users).

What has changed in the way of consuming the APIs:

* To make the connection it is necessary to replace the index "hash" by the indexes "access_key" and "secret_key" or send both in the index "hash" separated by 2 dots. Ex: "access_key:secret_key"(The system will define which API should be used by the 2 dots);
* A header called "Hestia-Exit-Code" with the code returned by the command is launched on requests;
* API will return a different http_code when an error occurs and for successful commands with empty output return "204";
* The "application/json" header is returned when the command returns a JSON.

2022-04-16 16:35 UTC, jaapmarcus reviewed
See comment due to Shellcheck

Need to check PHP8.1 doesn't produce errors

2022-04-16 16:35 UTC, jaapmarcus commented on bin/v-list-apis
> +    for api in $(ls $HESTIA/data/api/); do
Error in Shell check 
8221	               ^---------------------^ SC2045 (error): Iterating over ls output is fragile. Use globs.

2022-04-16 16:35 UTC, jaapmarcus commented on bin/v-list-apis
> +    for api in $(ls $HESTIA/data/api/); do
Same here

2022-04-16 16:35 UTC, jaapmarcus commented on bin/v-list-access-keys
> +    for key_file in $(ls $HESTIA/data/access-keys/); do
Same here

2022-04-16 16:35 UTC, jaapmarcus commented on bin/v-list-access-keys
> +    for key_file in $(ls $HESTIA/data/access-keys/); do
Same here

2022-04-18 11:21 UTC, ScIT-Raphael approved these changes

2022-04-18 17:13 UTC, jaapmarcus reviewed
It is missing an upgrade "path" from non existing setup to existing in 1.6.0.sh

2022-04-18 17:13 UTC, jaapmarcus commented on install/hst-install-debian.sh
> +write_config_value "API_V2" "0"
On Initial install it doesn't create the /usr/local/hestia/data/api key folder + copies the preset(s) to the folder

2022-04-18 17:13 UTC, jaapmarcus commented on install/hst-install-ubuntu.sh
> +write_config_value "API_V2" "0"
Also applies for here

2022-04-18 17:13 UTC, jaapmarcus commented on web/edit/server/index.php
> +    // Change API_V2
Current javascript hides the ip box when disabling legacy api. This should not happen.

2022-04-18 17:13 UTC, jaapmarcus commented on web/templates/pages/edit_server.html
>  														<table id="security_ip" style="<?php if ($_SESSION['API'] == "no") echo 'display:none;';?>">
IP box should not get hidden after Legacy is disabled

2022-04-18 17:13 UTC, jaapmarcus commented on web/templates/pages/add_access_key.html
> +                                <input type="text" size="20" class="vst-input" name="v_comment" maxlength="255"
2022/04/18 19:08:03 [error] 1012285#0: *30 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_comment in /usr/local/hestia/web/templates/pages/add_access_key.html on line 72PHP message: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/hestia/web/templates/pages/add_access_key.html on line 72" while reading response header from upstream,

2022-04-18 17:13 UTC, jaapmarcus commented on web/templates/pages/list_access_key.html
> +                                        <span style="font-size: 10pt; color:#ffd500;"><?= _('WARNING_TO_SAVE_ACCESS_KEY'); ?></span>
<img width="482" alt="Screenshot 2022-04-18 at 19 10 08" src="https://user-images.githubusercontent.com/9754650/163845333-6fae246b-66d1-4108-abe9-91dc941fde35.png">

With the dark theme it is hard to read we should probally change the color slightly

2022-04-18 17:13 UTC, jaapmarcus commented on install/hst-install-debian.sh
> +write_config_value "API_V2" "0"
We should probally enable it for admin user only on default if api is enabled

2022-04-19 07:31 UTC, jaapmarcus requested changes

2022-04-19 07:31 UTC, jaapmarcus commented on install/hst-install-debian.sh
> +    write_config_value "API" "no"
Untill we have fully finished the transition transition we should keep it enabled. for now

2022-04-19 07:31 UTC, jaapmarcus commented on install/hst-install-ubuntu.sh
> +    write_config_value "API" "no"
Untill we have fully finished the transition transition we should keep it enabled. for now

2022-04-19 09:54 UTC, jaapmarcus commented
Disabling legacy api "removed" api completely causing to break  the "new" api. 

Changes pushed solved the issue

2022-04-19 12:13 UTC, jhmaverick commented
Yesterday I didn't have time to check what needed to be changed in the edit/server index. But I think now everything is finished.

2022-04-19 16:01 UTC, jaapmarcus approved these changes

2022-04-20 11:58 UTC, merged

2022-06-20 06:01 UTC, vikasprogrammer commented
Do we have a documentation entry for this?

2022-06-20 06:22 UTC, jaapmarcus commented
https://github.com/hestiacp/hestiacp-docs/commit/b0e8a27f672e6af57197fb8e12369535690beb70

I push some changes to GitHub but for unknown reasons they are not merged yet on the live site

2022-06-20 07:02 UTC, jaapmarcus commented
https://docs.hestiacp.com/admin_docs/api.html#api-key-vs-password-vs-access-key