Ensure mail-wrapper.php use FQDN for hostname
hestiacp/hestiacp pull request #2805
Opened 2022-07-29 18:00 UTC by clarkchentw

For host configure as hostname and searching domain, this will ensure it output FQDN, non FQDN will result of sender become empty

E.g.
hostname: hestia
searching domain: example.com
FQDN hostname: hestia.example.com

Also tested with hostname hestia.example.com and searching domain example.com, it will still output hestia.example.com

2022-07-29 19:02 UTC, jaapmarcus commented
I assume you have the issues with Proxmox? 

eris@web02:~$ php -r "echo gethostname();"
web02

eris@web02:~$ php -r "echo gethostbyname(gethostname());"
x.x.x.x
eris@web02:~$ phpethostbyaddr(gethostbyname(gethostname()));"
web02.hostname.com

2022-07-30 01:09 UTC, clarkchentw commented
> I assume you have the issues with Proxmox?
> 
> eris@web02:~$ php -r "echo gethostname();" web02
> 
> eris@web02:~$ php -r "echo gethostbyname(gethostname());" x.x.x.x eris@web02:~$ phpethostbyaddr(gethostbyname(gethostname()));" web02.hostname.com

Yes

2022-07-30 11:57 UTC, jaapmarcus approved these changes

2022-07-31 11:40 UTC, divinity76 commented
can we add some safeguards against systems that are badly configured? consider:

```php
hans@cac4:~$ cat test.php
<?php
var_dump(
[
"gethostname()"=>gethostname(),
"gethostbyname(gethostname())"=>gethostbyname(gethostname()),
"gethostbyaddr(gethostbyname(gethostname()))"=>gethostbyaddr(gethostbyname(gethostname()))

]
);

hans@cac4:~$ php test.php
array(3) {
  ["gethostname()"]=>
  string(14) "cac4.ratma.net"
  ["gethostbyname(gethostname())"]=>
  string(9) "127.0.0.1"
  ["gethostbyaddr(gethostbyname(gethostname()))"]=>
  string(9) "localhost"
}
```

maybe something like:
```php
<?php

// Define vars
$hostname = (function():string{
    $badValues = array(false, null, 0, '', "localhost", "127.0.0.1", "::1", "0000:0000:0000:0000:0000:0000:0000:0001");
    $ret = gethostname();
    if(in_array($ret, $badValues, true)){
        throw new Exception('gethostname() failed');
    }
    $ret2 = gethostbyname($ret);
    if(in_array($ret2, $badValues, true)){
        return $ret;
    }
    $ret3 = gethostbyaddr($ret2);
    if(in_array($ret3, $badValues, true)){
        return $ret2;
    }
    return $ret3;
})();
```
which on the same badly configured system shown above, yields `string(22) "noreply@cac4.ratma.net"`

2022-07-31 11:40 UTC, divinity76 commented
can we add some safeguards against systems that are badly configured? consider:

```php
hans@cac4:~$ cat test.php
<?php
var_dump(
[
"gethostname()"=>gethostname(),
"gethostbyname(gethostname())"=>gethostbyname(gethostname()),
"gethostbyaddr(gethostbyname(gethostname()))"=>gethostbyaddr(gethostbyname(gethostname()))

]
);

hans@cac4:~$ php test.php
array(3) {
  ["gethostname()"]=>
  string(14) "cac4.ratma.net"
  ["gethostbyname(gethostname())"]=>
  string(9) "127.0.0.1"
  ["gethostbyaddr(gethostbyname(gethostname()))"]=>
  string(9) "localhost"
}
```

maybe something like:
```php
<?php

// Define vars
$hostname = (function():string{
    $badValues = array(false, null, 0, '', "localhost", "127.0.0.1", "::1", "0000:0000:0000:0000:0000:0000:0000:0001");
    $ret = gethostname();
    if(in_array($ret, $badValues, true)){
        throw new Exception('gethostname() failed');
    }
    $ret2 = gethostbyname($ret);
    if(in_array($ret2, $badValues, true)){
        return $ret;
    }
    $ret3 = gethostbyaddr($ret2);
    if(in_array($ret3, $badValues, true)){
        return $ret2;
    }
    return $ret3;
})();
```
which on the same badly configured system shown above, yields `string(22) "noreply@cac4.ratma.net"`

2022-07-31 11:44 UTC, jaapmarcus commented
Yes off course ...

2022-07-31 12:02 UTC, divinity76 requested changes, later dismissed
hoping we can add some safeguards like discussed here https://github.com/hestiacp/hestiacp/pull/2805#issuecomment-1200407448

2022-08-03 11:24 UTC, jaapmarcus commented
Made the changes @divinity76  created and it works fine on my test server.

2022-08-03 12:36 UTC, merged