Update jail.local
hestiacp/hestiacp pull request #2856
Opened 2022-08-19 09:01 UTC by jlguerrerosanz

Added 3 commented lines with a thorough example of the ignoreip parameter.

2022-08-19 09:04 UTC, jaapmarcus requested changes
Please keep[ /install/rpm/fail2ban/jail.local ](https://github.com/hestiacp/hestiacp/blob/main/install/rpm/fail2ban/jail.local) in sync

Also 

https://github.com/hestiacp/hestiacp/blob/712de8d538f636a3bfa9b34626de6743a18e9b58/test/test.bats#L1880

And adding your ip in there will do the same.

2022-08-19 09:09 UTC, jlguerrerosanz reviewed
Done

2022-08-19 09:21 UTC, jaapmarcus approved these changes

2022-08-21 15:12 UTC, merged

2022-08-21 17:20 UTC, jlguerrerosanz commented
Yay!