Add support for DNSSEC
hestiacp/hestiacp pull request #2938
Opened 2022-09-21 17:34 UTC by jaapmarcus

Please not this PR is not stable and should not be used in production

Due the price raises for .ch domain without DNSSEC support it made sense to add support for it.

Please note Syncing "Hestia" API will not get supported due to issues with it. 

To enable it change manually edit DNSSEC in /usr/local/hestia/data/user/{user}/dns.conf and set DNSSEC='no' to 'yes' or add "DNSSEC='yes'

Then rebuild it.

2022-09-21 17:47 UTC, ScIT-Raphael requested changes

2022-09-21 17:47 UTC, ScIT-Raphael commented on func/rebuild.sh
> +        sed -i "/dns\/weetjes.net.db/d" $dns_conf
hardcoded domain name left :)

2022-09-23 14:00 UTC, jaapmarcus commented
Todo list

1. Restore Backup
2. Syncing 
3. Idn support / check
4 general testing

2022-10-02 19:49 UTC, jaapmarcus commented
UI It self might need some ❤️ 

![Screenshot 2022-10-02 at 21 48 32](https://user-images.githubusercontent.com/9754650/193473380-914eba8d-6845-4d70-97fc-0afb85090d98.png)

2022-10-04 09:45 UTC, jaapmarcus commented
**Do not update to this branch if your server contains critical domains**

Install branch:
Run `v-update-sys-hestia-git jaapmarcus feature/dnssec-support`

If you are planning to use it under a "single" setup without any "DNS cluster" just enable DNSSEC and run `v-list-dnssec-public-key user domain.com plain DS ` or `v-list-dnssec-public-key user domain.com plain` to get the required DS or DNSKEY 

For setting up a DNS Cluster:
On the "master" 

Run `v-update-sys-hestia-git jaapmarcus feature/dnssec-support`

nano /usr/local/hestia/conf/hestia.conf

And edit: DNS_CLUSTER_SYSTEM='hestia' to DNS_CLUSTER_SYSTEM='zone'

Open /etc/bind/named.options  and change the following:

`       allow-transfer {"none";};`
Remove "none" and add your slaves ip separated by a ;
Add 
`also-notify { slaveip; };`

On your slave:
Run `v-update-sys-hestia-git jaapmarcus feature/dnssec-support`

Open /etc/bind/named.options  and change the following:

`       allow-recursion { 127.0.0.1; ::1;};;`
Add masterip; 

Add 
`allow-notify{ masterip; };`

Now setup the slave as you would normally do.

2022-10-21 07:45 UTC, ScIT-Raphael approved these changes
Testing went properly, couldnt find any bug.

2022-10-21 07:45 UTC, merged