Prevent email variable update if is already set
hestiacp/hestiacp pull request #2970
Opened 2022-10-13 21:47 UTC by manuelserol

When restoring backups that include web domains the notification email is replaced by info@first_web_domain_in_restore_list preventing the user to receive a confirmation or error email with restore log

2022-10-13 22:39 UTC, jaapmarcus commented
We should rename the restore email or fetch it at a later date instead. This will publish the user email in nginx / apache2 config

2022-10-13 22:41 UTC, jaapmarcus commented
https://github.com/hestiacp/hestiacp/blob/508d3f163d93293fc8afb39c3ae512c5bdf30f63/bin/v-restore-user#L102

Rename to something else makes more sense...

2022-10-14 05:52 UTC, jaapmarcus requested changes
This will store the email of the user in nginx / apache2 config .

No fan of it...

2022-10-14 13:41 UTC, manuelserol commented
> 

Do you mean rename the email variable all across the v-restore-user file?

2022-10-14 13:45 UTC, jaapmarcus commented
Yes

2022-10-14 14:35 UTC, jaapmarcus commented
We should just remove the line:

email="info@$domain"

2022-10-14 14:39 UTC, jaapmarcus commented
Replaced with: 
https://github.com/hestiacp/hestiacp/commit/ccdb4c5cb01dd59af0ded21f39e682cea3409ec8

2022-10-14 14:39 UTC, closed without merging