Add config to avoid restarting daemons on error
hestiacp/hestiacp pull request #3183
Opened 2023-01-03 16:57 UTC by joelakuhn

I'm not sure if this should be a feature or fix. When calling `v-restart-cron`, `v-restart-dns`, `v-restart-ftp`, `v-restart-proxy`, or `v-restart-web`, the `send_email_report` function will restart the service causing it to die. This behavior is surprising, because the function is only called when a configuration error is detected, yet it restarts the service anyways, resulting in unforced downtime.

The use of this behavior is to capture the error output of the restarted service to add to the notification, but each of these scripts already capture the output of `nginx -t`, `named-checkconf`, etc. so enough error context should already be available, and I don't believe whatever value is achieved in including the failed restart output is outweighed by the downtime caused.

This patch adds a configuration variable `NO_RESTART_ON_CONF_ERR` that must be set to `'yes'` in order to avoid restarting the daemon in the case of a configuration error. This makes the feature opt-in, though I honestly think the restart line should just be removed.

2023-01-03 17:58 UTC, jaapmarcus commented
It is missing the updates in hst-install-ubuntu.sh 

And for existing installs:

We need to add it hestia.conf aswell easiest method is via 

https://github.com/hestiacp/hestiacp/blob/44314eb8ad07eac8a477ea4e26ec6b4976232781/func/syshealth.sh#L399-L403]

2023-01-04 11:05 UTC, jaapmarcus requested changes
See comment..

2023-01-04 14:22 UTC, joelakuhn commented
I added the config to `func/syshealth.sh` and `install/hst-install-ubuntu.sh`.

2023-01-05 11:35 UTC, jaapmarcus commented
Changes look fine as requested. 

Just took some time to see if this behaviour is correct or not. And I don't think this is the best solution (Also the old one is broken imo)
For non Web services: 
1.  We restart the service
2. It triggers an error so $? != 0 and we send an email running the config test and catch the error output to create an email report

For Web service:
1. Run a config test and see if an error is present and then still use the function to test / restart
2.  We restart the service
3. It triggers an error so $? != 0 and we send an email running the config test and catch the error output to create an email report

As the service is all ready down the restart should not matter.

My suggestion would be:
Step 1: Preform config test
On Failure:  Send out an email to the admin that that a config error is present do not restart!
On Success: Step 2:

Step 2: Preform a restart
On a failure: Send out an email to the admin with both config test and the restart output
On success 🥳  And do nothing. 

We don't need to add the new variable. And it should make the system more reliable.

Feel free shoot some ideas...

2023-01-05 21:40 UTC, joelakuhn commented
@jaapmarcus That seems like a good plan to me. I wanted change the least behavior in my pull since I'm not a regular here, so I'm totally happy if this sparks a more robust solution.

I missed the fact that cron doesn't do a config test, and doesn't seem to have that ability. Also, vsftpd is in the same boat, so I'm not sure it would be possible to check for errors before restarting that.

This is probably beyond the scope of this pull at this point, but I'll go ahead and push my new configuration based on your suggestion.

2023-01-05 22:09 UTC, jaapmarcus commented
> 

For those cases it is probably shit happens at least vsftpd / cron are services where the server is still reachable via ssh and users can still fix it if they want... 

We should also do the same for other servers as ssh, php, exim, dovecot, iptables and databases...

2023-01-08 10:03 UTC, jaapmarcus approved these changes

2023-01-19 10:31 UTC, merged