Start cleaning up templates
hestiacp/hestiacp pull request #3217
Opened 2023-01-20 22:09 UTC by jakobbouchard

I'm starting to cleanup the markup for page templates, as well as convert their JavaScript over to Alpine. This is very much a work in progress, and with my 7 courses this semester, it might take a while to finish it. But at least now it will be a lot more readable, and will remove a lot of repetition and useless JS.

2023-01-20 22:11 UTC, jaapmarcus commented
When ever possible I prefer smaller "merges" and more frequent then 1 or 2 very large merges :)

2023-01-20 23:25 UTC, jakobbouchard commented
@jaapmarcus would you prefer that I do it one page at a time? In fact, it might make it easier for me too

2023-01-20 23:50 UTC, jaapmarcus commented
> @jaapmarcus would you prefer that I do it one page at a time? In fact, it might make it easier for me too

That is fine for me.. (Or few at the time depending on size and what suits you)

We have done @AlecRust  massive css rewrite almost the same and it works fine.  (And still in progress) It also allows

2023-01-30 21:37 UTC, jaapmarcus commented
@jakobbouchard  is this PR ready for review?

2023-01-31 10:02 UTC, jaapmarcus commented on web/templates/pages/list_ssl.php
> +				<textarea
I am getting: 
<img width="1452" alt="Screenshot 2023-01-31 at 11 02 10" src="https://user-images.githubusercontent.com/9754650/215729213-a3567bcf-d540-4f9e-86c2-6a33ae272e15.png">
<img width="789" alt="Screenshot 2023-01-31 at 11 00 55" src="https://user-images.githubusercontent.com/9754650/215729220-1bf3c628-c72d-4843-8e27-692428a2c79d.png">

2023-01-31 10:04 UTC, jaapmarcus requested changes
Also on Quick install clicking on generate will submit the form:

[Error] ReferenceError: Can't find variable: $
	Global Code (webapp:599)

2023-02-05 02:51 UTC, jakobbouchard commented
@jaapmarcus I fixed both issues. The first one was due to certificates having newlines, so I base64 encode the value in the HTML, then decode it for the download blob and textarea value.

As for the second one, it was simply a mistake when changing empty (`href="#"`) links to buttons, some of them should have `type="button"` on them, since by default they submit the form at the same time as executing related code.

2023-02-05 12:50 UTC, jaapmarcus approved these changes

2023-02-05 12:50 UTC, jaapmarcus commented
Works fine

2023-02-05 12:50 UTC, merged