Fix/v-add-sys-quota and v-delete-sys-quota
hestiacp/hestiacp pull request #3991
Opened 2023-09-08 07:06 UTC by sahsanu

This PR comes from this post https://forum.hestiacp.com/t/disk-quota-exceeded/10620

I completely forgot this issue so here we go to try to fix it ;)

`v-add-sys-quota`:

**1.-** It uses command `which --skip-alias --skip-functions quota` and those `--skip` options are not available in regular `which` command installed neither in Debian nor Ubuntu so I replaced it with `type -P quota`

`v-delete-sys-quota`:

**1.-** If a fstab file contains something like this:
```
# / was on /dev/sda1 during installation
UUID=example-aaaa-bbbb-cccc-dddddddddddd /               ext4    errors=remount-ro 0
```

The script will match both lines even if the first one is a comment. `v-add-sys-quota` manages it correctly so I fixed `v-delete-sys-quota` script.

**2.-** It uses command `which --skip-alias --skip-functions quotaoff` and those `--skip` options are not available in regular `which` command installed neither in Debian nor Ubuntu so I replaced it with `type -P quotaoff`

I've also made other minimal changes, like remove `/forcequotacheck` when using `v-delete-sys-quota` script and also I've changed some `ìf` to avoid the use of a variable and then check the return code.

2023-09-08 22:28 UTC, jaapmarcus commented on bin/v-delete-sys-quota
> +	sed -i "s/DISK_QUOTA=.*/DISK_QUOTA='no'/g" "$HESTIA/conf/hestia.conf"
$BIN/v-change-sys-config-value "DISK_QUOTA" "no"

Saves the check and make it consistent with rest of code...

We should also update line 83-87 in v-add-sys-quota

2023-09-08 22:31 UTC, jaapmarcus requested changes
After running: 

v-delete-sys-quota I see the error message:
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.

2023-09-09 06:45 UTC, sahsanu commented
Added systemctl daemon-reload before mount and use v-change-sys-config-value to modify DISK_QUOTA value.

Regarding `systemctl daemon-reload`, I saw it when I was testing the scripts but I'm so used to run `systemctl` manually that didn't think to include it in the scripts :)

2023-09-09 07:02 UTC, sahsanu commented
Too early in the morning to modify code. I didn't understand your sentence 'save the check' and I see function `change_sys_value`  already checks the variable and also adds it if is not there. New commit in a few minutes ;)

2023-09-09 21:03 UTC, jaapmarcus approved these changes

2023-09-09 21:04 UTC, merged