Add timezone to Cron pages
hestiacp/hestiacp pull request #4228
Opened 2024-01-10 11:26 UTC by 0pc0deFR

This pull request add system timezone to cron pages.

It's an alternative for issue #2368

2024-01-10 11:40 UTC, AlecRust commented on web/templates/pages/add_cron.php
> +			</div>
```suggestion
      <p class="u-mb20">
        <?= _('System timezone') ?>: <span class="u-text-bold"><?= $v_timezone ?></span>
      </p>
```

2024-01-10 11:40 UTC, AlecRust commented on web/templates/pages/list_cron.php
> +						<i class="fas fa-toggle-off icon-green"></i><?= _("Disable Notifications") ?>
Why have you changed this to `off`?

2024-01-10 11:40 UTC, AlecRust commented on web/templates/pages/list_cron.php
> +<footer class="app-footer">
Why have you added the global app footer in this template? This should already be included by `includes/app_footer.php`.

2024-01-10 12:03 UTC, jaapmarcus requested changes
Please revert the changes of the last commit Docuwiki..

2024-01-10 12:08 UTC, 0pc0deFR commented
> Please revert the changes of the last commit Docuwiki..

Yes, I'm sorry

2024-01-10 12:26 UTC, AlecRust commented
@0pc0deFR you seem to be resolving my comments without addressing them?

2024-01-10 16:26 UTC, 0pc0deFR commented
> @0pc0deFR you seem to be resolving my comments without addressing them?

It's modified now.

2024-01-10 16:31 UTC, AlecRust commented on web/templates/pages/add_cron.php
> +			</div>
@0pc0deFR can you use this in all cases please?

2024-01-12 23:05 UTC, AlecRust commented
I've created #4236 for this.

2024-01-12 23:05 UTC, closed without merging