Remove PHP code, and fix installer warning
hestiacp/hestiacp pull request #4279
Opened 2024-02-01 20:44 UTC by Skamasle

When install hestia, 

Installer first add user and then install PHP, so this php code return a warning 

/usr/local/hestia/bin/v-add-user: line 36: php: command not found

So why add php code to pure bash script :/

2024-02-01 20:59 UTC, Skamasle commented
Dont like you shellcheck... :/

2024-02-01 21:05 UTC, Skamasle commented
So, code works fine, but as I understand the shellcheck error not accept this kind of array check, need make some for loop to check each element in array to be valid, 

So more lines of code for same result

2024-02-01 22:30 UTC, jaapmarcus requested changes

2024-02-01 22:30 UTC, jaapmarcus commented on bin/v-add-user
> +	if [[ "${reserved_names[@],,}" =~ "${user,,}" ]]; then
Does not really work as expected... 

root@dev:~# v-add-user buffer 1234 info@hestiacp.com
Error: The user name 'buffer' is reserved and cannot be used. List of reserved names: aria aria_log mysql mysql_upgrade ib ib_buffer ddl ddl_recovery performance sudo

buffer or even pref should be allowed as user names..

2024-02-02 09:56 UTC, jaapmarcus approved these changes

2024-02-02 09:57 UTC, merged